### Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: bXlyb290Cg==
type: Opaque

### Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjR0Z5YzJocGJqb2pXRzkwYjIxbE5Iaz0iCgkJfSwKCQkiZ2l0bGFiLnByYWt0aWt1bS1zZXJ2aWNlcy5ydTo1MDUwIjogewoJCQkiYXV0aCI6ICJaMmwwYkdGaUxXTnBMWFJ2YTJWdU9uTmpWR1JSVGxCU2FrTjZhbmN6TFZwcFRVSkUiCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJjR0Z5YzJocGJuQTZWRWhoWTBoaGNtTmxUMlJQYzBVMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson