---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-store-configmap
data:
  sausage-store.conf: |
    server {

      listen 8080;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8081;
      }
    }
