---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 2
  ## Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять поды порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/parshin/sausage-store/sausage-backend-report:1.0.64646
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_VAULT_HOST
              value: 130.193.38.73
            - name: SPRING_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret